use_frameworks!

platform :ios, '10.0'

target 'WSCalendarViewSwift_Example' do
  pod 'WSCalendarViewSwift', :path => '../'

  target 'WSCalendarViewSwift_Tests' do
    inherit! :search_paths

    
  end
end
